# Generated by Django 3.1.2 on 2022-01-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='alias',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
