# Generated by Django 3.1.2 on 2022-02-23 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='arp_destination_ip',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='packet',
            name='arp_destination_mac',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='packet',
            name='arp_source_ip',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='packet',
            name='arp_source_mac',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='packet',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 3, 32, 16, 748861, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='packet',
            name='raw_packet_data',
            field=models.CharField(default=None, max_length=65535),
        ),
        migrations.AddField(
            model_name='packet',
            name='upd_destination_port',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='packet',
            name='upd_source_port',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 3, 32, 16, 747865, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 3, 32, 16, 747865, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packet',
            name='ethernet_destination',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='packet',
            name='ethernet_source',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='packet',
            name='ip_destination',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='packet',
            name='ip_source',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='packet',
            name='tcp_destination_port',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='packet',
            name='tcp_flag',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='packet',
            name='tcp_source_port',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
