# Generated by Django 3.1.2 on 2022-02-23 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0005_auto_20220223_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 18, 6, 39, 666498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 18, 6, 39, 666498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packet',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 18, 6, 39, 666498, tzinfo=utc)),
        ),
    ]
