# Generated by Django 3.1.2 on 2022-02-23 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0008_auto_20220223_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet',
            old_name='dns_packet_qr',
            new_name='dns_packet_qd',
        ),
        migrations.AlterField(
            model_name='device',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 18, 30, 34, 745831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 18, 30, 34, 745831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packet',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 18, 30, 34, 746833, tzinfo=utc)),
        ),
    ]
