# Generated by Django 3.1.2 on 2022-03-28 00:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0011_auto_20220327_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gateway',
        ),
        migrations.AlterField(
            model_name='device',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 0, 32, 21, 134768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 0, 32, 21, 134768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='packet',
            name='date_found',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 0, 32, 21, 135765, tzinfo=utc)),
        ),
    ]
